//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
public let R = _R(bundle: Bundle(for: BundleFinder.self))

public struct _R: Sendable {
  public let bundle: Foundation.Bundle
  public init(bundle: Foundation.Bundle) {
    self.bundle = bundle
  }
  public var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }

  public func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  public func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  public func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  public func validate() throws {

  }

  public struct project: Sendable {
    public let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  public struct string: Sendable {
    public let bundle: Foundation.Bundle
    public let preferredLanguages: [String]?
    public let locale: Locale?
    public init(bundle: Foundation.Bundle, preferredLanguages: [String]? = nil, locale: Locale? = nil) {
      self.bundle = bundle
      self.preferredLanguages = preferredLanguages
      self.locale = locale
    }
    public var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    public func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 63 localization keys.
    public struct localizable: Sendable {
      public let source: RswiftResources.StringResource.Source
      public init(source: RswiftResources.StringResource.Source) {
        self.source = source
      }

      /// en translation: Confirm Password
      ///
      /// Key: auth.confirmPasswordPlaceholder
      ///
      /// Locales: en
      public var authConfirmPasswordPlaceholder: RswiftResources.StringResource { .init(key: "auth.confirmPasswordPlaceholder", tableName: "Localizable", source: source, developmentValue: "Confirm Password", comment: nil) }

      /// en translation: Create account
      ///
      /// Key: auth.createAccountButtonTitle
      ///
      /// Locales: en
      public var authCreateAccountButtonTitle: RswiftResources.StringResource { .init(key: "auth.createAccountButtonTitle", tableName: "Localizable", source: source, developmentValue: "Create account", comment: nil) }

      /// en translation: Email
      ///
      /// Key: auth.emailPlaceholder
      ///
      /// Locales: en
      public var authEmailPlaceholder: RswiftResources.StringResource { .init(key: "auth.emailPlaceholder", tableName: "Localizable", source: source, developmentValue: "Email", comment: nil) }

      /// en translation: Forgot password?
      ///
      /// Key: auth.forgotPasswordButtonTitle
      ///
      /// Locales: en
      public var authForgotPasswordButtonTitle: RswiftResources.StringResource { .init(key: "auth.forgotPasswordButtonTitle", tableName: "Localizable", source: source, developmentValue: "Forgot password?", comment: nil) }

      /// en translation: Flick
      ///
      /// Key: auth.navigationTitle
      ///
      /// Locales: en
      public var authNavigationTitle: RswiftResources.StringResource { .init(key: "auth.navigationTitle", tableName: "Localizable", source: source, developmentValue: "Flick", comment: nil) }

      /// en translation: Password
      ///
      /// Key: auth.passwordPlaceholder
      ///
      /// Locales: en
      public var authPasswordPlaceholder: RswiftResources.StringResource { .init(key: "auth.passwordPlaceholder", tableName: "Localizable", source: source, developmentValue: "Password", comment: nil) }

      /// en translation: Reset password
      ///
      /// Key: auth.resetPasswordButtonTitle
      ///
      /// Locales: en
      public var authResetPasswordButtonTitle: RswiftResources.StringResource { .init(key: "auth.resetPasswordButtonTitle", tableName: "Localizable", source: source, developmentValue: "Reset password", comment: nil) }

      /// en translation: Reset password
      ///
      /// Key: auth.resetPasswordTitle
      ///
      /// Locales: en
      public var authResetPasswordTitle: RswiftResources.StringResource { .init(key: "auth.resetPasswordTitle", tableName: "Localizable", source: source, developmentValue: "Reset password", comment: nil) }

      /// en translation: Save password
      ///
      /// Key: auth.savePasswordButtonTitle
      ///
      /// Locales: en
      public var authSavePasswordButtonTitle: RswiftResources.StringResource { .init(key: "auth.savePasswordButtonTitle", tableName: "Localizable", source: source, developmentValue: "Save password", comment: nil) }

      /// en translation: Already have an account?
      ///
      /// Key: auth.signInButtonDescription
      ///
      /// Locales: en
      public var authSignInButtonDescription: RswiftResources.StringResource { .init(key: "auth.signInButtonDescription", tableName: "Localizable", source: source, developmentValue: "Already have an account?", comment: nil) }

      /// en translation: Sign in
      ///
      /// Key: auth.signInButtonTitle
      ///
      /// Locales: en
      public var authSignInButtonTitle: RswiftResources.StringResource { .init(key: "auth.signInButtonTitle", tableName: "Localizable", source: source, developmentValue: "Sign in", comment: nil) }

      /// en translation: Login to your account
      ///
      /// Key: auth.signInTitle
      ///
      /// Locales: en
      public var authSignInTitle: RswiftResources.StringResource { .init(key: "auth.signInTitle", tableName: "Localizable", source: source, developmentValue: "Login to your account", comment: nil) }

      /// en translation: Don`t have an account?
      ///
      /// Key: auth.signUpButtonDescription
      ///
      /// Locales: en
      public var authSignUpButtonDescription: RswiftResources.StringResource { .init(key: "auth.signUpButtonDescription", tableName: "Localizable", source: source, developmentValue: "Don`t have an account?", comment: nil) }

      /// en translation: SignUp
      ///
      /// Key: auth.signUpButtonTitle
      ///
      /// Locales: en
      public var authSignUpButtonTitle: RswiftResources.StringResource { .init(key: "auth.signUpButtonTitle", tableName: "Localizable", source: source, developmentValue: "SignUp", comment: nil) }

      /// en translation: Create your account
      ///
      /// Key: auth.signUpTitle
      ///
      /// Locales: en
      public var authSignUpTitle: RswiftResources.StringResource { .init(key: "auth.signUpTitle", tableName: "Localizable", source: source, developmentValue: "Create your account", comment: nil) }

      /// en translation: Username
      ///
      /// Key: auth.usernamePlaceholder
      ///
      /// Locales: en
      public var authUsernamePlaceholder: RswiftResources.StringResource { .init(key: "auth.usernamePlaceholder", tableName: "Localizable", source: source, developmentValue: "Username", comment: nil) }

      /// en translation: Movies
      ///
      /// Key: contentToggle.moviesTitle
      ///
      /// Locales: en
      public var contentToggleMoviesTitle: RswiftResources.StringResource { .init(key: "contentToggle.moviesTitle", tableName: "Localizable", source: source, developmentValue: "Movies", comment: nil) }

      /// en translation: TV Series
      ///
      /// Key: contentToggle.showsTitle
      ///
      /// Locales: en
      public var contentToggleShowsTitle: RswiftResources.StringResource { .init(key: "contentToggle.showsTitle", tableName: "Localizable", source: source, developmentValue: "TV Series", comment: nil) }

      /// en translation: Airing today
      ///
      /// Key: home.airingTodayShowsSectionTitle
      ///
      /// Locales: en
      public var homeAiringTodayShowsSectionTitle: RswiftResources.StringResource { .init(key: "home.airingTodayShowsSectionTitle", tableName: "Localizable", source: source, developmentValue: "Airing today", comment: nil) }

      /// en translation: Home
      ///
      /// Key: home.navigationTitle
      ///
      /// Locales: en
      public var homeNavigationTitle: RswiftResources.StringResource { .init(key: "home.navigationTitle", tableName: "Localizable", source: source, developmentValue: "Home", comment: nil) }

      /// en translation: Now playing
      ///
      /// Key: home.nowPlayingMoviesSectionTitle
      ///
      /// Locales: en
      public var homeNowPlayingMoviesSectionTitle: RswiftResources.StringResource { .init(key: "home.nowPlayingMoviesSectionTitle", tableName: "Localizable", source: source, developmentValue: "Now playing", comment: nil) }

      /// en translation: On TV
      ///
      /// Key: home.onTVShowsSectionTitle
      ///
      /// Locales: en
      public var homeOnTVShowsSectionTitle: RswiftResources.StringResource { .init(key: "home.onTVShowsSectionTitle", tableName: "Localizable", source: source, developmentValue: "On TV", comment: nil) }

      /// en translation: Popular
      ///
      /// Key: home.popularMoviesSectionTitle
      ///
      /// Locales: en
      public var homePopularMoviesSectionTitle: RswiftResources.StringResource { .init(key: "home.popularMoviesSectionTitle", tableName: "Localizable", source: source, developmentValue: "Popular", comment: nil) }

      /// en translation: Popular
      ///
      /// Key: home.popularShowsSectionTitle
      ///
      /// Locales: en
      public var homePopularShowsSectionTitle: RswiftResources.StringResource { .init(key: "home.popularShowsSectionTitle", tableName: "Localizable", source: source, developmentValue: "Popular", comment: nil) }

      /// en translation: See all
      ///
      /// Key: home.sectionHeaderButtonTitle
      ///
      /// Locales: en
      public var homeSectionHeaderButtonTitle: RswiftResources.StringResource { .init(key: "home.sectionHeaderButtonTitle", tableName: "Localizable", source: source, developmentValue: "See all", comment: nil) }

      /// en translation: Top Rated
      ///
      /// Key: home.topRatedMoviesSectionTitle
      ///
      /// Locales: en
      public var homeTopRatedMoviesSectionTitle: RswiftResources.StringResource { .init(key: "home.topRatedMoviesSectionTitle", tableName: "Localizable", source: source, developmentValue: "Top Rated", comment: nil) }

      /// en translation: Top Rated
      ///
      /// Key: home.topRatedShowsSectionTitle
      ///
      /// Locales: en
      public var homeTopRatedShowsSectionTitle: RswiftResources.StringResource { .init(key: "home.topRatedShowsSectionTitle", tableName: "Localizable", source: source, developmentValue: "Top Rated", comment: nil) }

      /// en translation: Upcoming
      ///
      /// Key: home.upcomingMoviesSectionTitle
      ///
      /// Locales: en
      public var homeUpcomingMoviesSectionTitle: RswiftResources.StringResource { .init(key: "home.upcomingMoviesSectionTitle", tableName: "Localizable", source: source, developmentValue: "Upcoming", comment: nil) }

      /// en translation: Budget
      ///
      /// Key: itemDetails.budgetSectionTitle
      ///
      /// Locales: en
      public var itemDetailsBudgetSectionTitle: RswiftResources.StringResource { .init(key: "itemDetails.budgetSectionTitle", tableName: "Localizable", source: source, developmentValue: "Budget", comment: nil) }

      /// en translation: Cast
      ///
      /// Key: itemDetails.castNavigationTitle
      ///
      /// Locales: en
      public var itemDetailsCastNavigationTitle: RswiftResources.StringResource { .init(key: "itemDetails.castNavigationTitle", tableName: "Localizable", source: source, developmentValue: "Cast", comment: nil) }

      /// en translation: Cast
      ///
      /// Key: itemDetails.castSectionTitle
      ///
      /// Locales: en
      public var itemDetailsCastSectionTitle: RswiftResources.StringResource { .init(key: "itemDetails.castSectionTitle", tableName: "Localizable", source: source, developmentValue: "Cast", comment: nil) }

      /// en translation: Language
      ///
      /// Key: itemDetails.languageSectionTitle
      ///
      /// Locales: en
      public var itemDetailsLanguageSectionTitle: RswiftResources.StringResource { .init(key: "itemDetails.languageSectionTitle", tableName: "Localizable", source: source, developmentValue: "Language", comment: nil) }

      /// en translation: Network
      ///
      /// Key: itemDetails.networkSectionTitle
      ///
      /// Locales: en
      public var itemDetailsNetworkSectionTitle: RswiftResources.StringResource { .init(key: "itemDetails.networkSectionTitle", tableName: "Localizable", source: source, developmentValue: "Network", comment: nil) }

      /// en translation: Recommendations
      ///
      /// Key: itemDetails.recommendationsSectionTitle
      ///
      /// Locales: en
      public var itemDetailsRecommendationsSectionTitle: RswiftResources.StringResource { .init(key: "itemDetails.recommendationsSectionTitle", tableName: "Localizable", source: source, developmentValue: "Recommendations", comment: nil) }

      /// en translation: Revenue
      ///
      /// Key: itemDetails.revenueSectionTitle
      ///
      /// Locales: en
      public var itemDetailsRevenueSectionTitle: RswiftResources.StringResource { .init(key: "itemDetails.revenueSectionTitle", tableName: "Localizable", source: source, developmentValue: "Revenue", comment: nil) }

      /// en translation: Reviews
      ///
      /// Key: itemDetails.reviewDetailsNavigationTitle
      ///
      /// Locales: en
      public var itemDetailsReviewDetailsNavigationTitle: RswiftResources.StringResource { .init(key: "itemDetails.reviewDetailsNavigationTitle", tableName: "Localizable", source: source, developmentValue: "Reviews", comment: nil) }

      /// en translation: A review by %@
      ///
      /// Key: itemDetails.reviewHeaderTitle
      ///
      /// Locales: en
      public var itemDetailsReviewHeaderTitle: RswiftResources.StringResource1<String> { .init(key: "itemDetails.reviewHeaderTitle", tableName: "Localizable", source: source, developmentValue: "A review by %@", comment: nil) }

      /// en translation: Reviews
      ///
      /// Key: itemDetails.reviewsNavigationTitle
      ///
      /// Locales: en
      public var itemDetailsReviewsNavigationTitle: RswiftResources.StringResource { .init(key: "itemDetails.reviewsNavigationTitle", tableName: "Localizable", source: source, developmentValue: "Reviews", comment: nil) }

      /// en translation: Reviews (%d)
      ///
      /// Key: itemDetails.reviewsSectionTitle
      ///
      /// Locales: en
      public var itemDetailsReviewsSectionTitle: RswiftResources.StringResource1<Int> { .init(key: "itemDetails.reviewsSectionTitle", tableName: "Localizable", source: source, developmentValue: "Reviews (%d)", comment: nil) }

      /// en translation: Status
      ///
      /// Key: itemDetails.statusSectionTitle
      ///
      /// Locales: en
      public var itemDetailsStatusSectionTitle: RswiftResources.StringResource { .init(key: "itemDetails.statusSectionTitle", tableName: "Localizable", source: source, developmentValue: "Status", comment: nil) }

      /// en translation: Trailer
      ///
      /// Key: itemDetails.trailerButtonTitle
      ///
      /// Locales: en
      public var itemDetailsTrailerButtonTitle: RswiftResources.StringResource { .init(key: "itemDetails.trailerButtonTitle", tableName: "Localizable", source: source, developmentValue: "Trailer", comment: nil) }

      /// en translation: Type
      ///
      /// Key: itemDetails.typeSectionTitle
      ///
      /// Locales: en
      public var itemDetailsTypeSectionTitle: RswiftResources.StringResource { .init(key: "itemDetails.typeSectionTitle", tableName: "Localizable", source: source, developmentValue: "Type", comment: nil) }

      /// en translation: Where to watch
      ///
      /// Key: itemDetails.whereToWatchButtonTitle
      ///
      /// Locales: en
      public var itemDetailsWhereToWatchButtonTitle: RswiftResources.StringResource { .init(key: "itemDetails.whereToWatchButtonTitle", tableName: "Localizable", source: source, developmentValue: "Where to watch", comment: nil) }

      /// en translation: My Favorites
      ///
      /// Key: myFavorites.navigationTitle
      ///
      /// Locales: en
      public var myFavoritesNavigationTitle: RswiftResources.StringResource { .init(key: "myFavorites.navigationTitle", tableName: "Localizable", source: source, developmentValue: "My Favorites", comment: nil) }

      /// en translation: Discover your favorite movies & TV shows
      ///
      /// Key: onboarding.firstPageTitle
      ///
      /// Locales: en
      public var onboardingFirstPageTitle: RswiftResources.StringResource { .init(key: "onboarding.firstPageTitle", tableName: "Localizable", source: source, developmentValue: "Discover your favorite\nmovies & TV shows", comment: nil) }

      /// en translation: Stay up with new releases
      ///
      /// Key: onboarding.fourthPageTitle
      ///
      /// Locales: en
      public var onboardingFourthPageTitle: RswiftResources.StringResource { .init(key: "onboarding.fourthPageTitle", tableName: "Localizable", source: source, developmentValue: "Stay up with\nnew releases", comment: nil) }

      /// en translation: Get Started
      ///
      /// Key: onboarding.getStartedButtonTitle
      ///
      /// Locales: en
      public var onboardingGetStartedButtonTitle: RswiftResources.StringResource { .init(key: "onboarding.getStartedButtonTitle", tableName: "Localizable", source: source, developmentValue: "Get Started", comment: nil) }

      /// en translation: Express your opinion in ratings and reviews
      ///
      /// Key: onboarding.secondPageTitle
      ///
      /// Locales: en
      public var onboardingSecondPageTitle: RswiftResources.StringResource { .init(key: "onboarding.secondPageTitle", tableName: "Localizable", source: source, developmentValue: "Express your opinion\nin ratings and reviews", comment: nil) }

      /// en translation: Skip
      ///
      /// Key: onboarding.skipButtonTitle
      ///
      /// Locales: en
      public var onboardingSkipButtonTitle: RswiftResources.StringResource { .init(key: "onboarding.skipButtonTitle", tableName: "Localizable", source: source, developmentValue: "Skip", comment: nil) }

      /// en translation: Add the best movies & TV Shows to favorites
      ///
      /// Key: onboarding.thirdPageTitle
      ///
      /// Locales: en
      public var onboardingThirdPageTitle: RswiftResources.StringResource { .init(key: "onboarding.thirdPageTitle", tableName: "Localizable", source: source, developmentValue: "Add the best movies &\nTV Shows to favorites", comment: nil) }

      /// en translation: Start search right now!
      ///
      /// Key: search.listPlaceholder
      ///
      /// Locales: en
      public var searchListPlaceholder: RswiftResources.StringResource { .init(key: "search.listPlaceholder", tableName: "Localizable", source: source, developmentValue: "Start search right now!", comment: nil) }

      /// en translation: Search
      ///
      /// Key: search.navigationTitle
      ///
      /// Locales: en
      public var searchNavigationTitle: RswiftResources.StringResource { .init(key: "search.navigationTitle", tableName: "Localizable", source: source, developmentValue: "Search", comment: nil) }

      /// en translation: No search results.
      ///
      /// Key: search.noResultsPlaceholder
      ///
      /// Locales: en
      public var searchNoResultsPlaceholder: RswiftResources.StringResource { .init(key: "search.noResultsPlaceholder", tableName: "Localizable", source: source, developmentValue: "No search results.", comment: nil) }

      /// en translation: Search for a movie, TV series...
      ///
      /// Key: search.searchPlaceholder
      ///
      /// Locales: en
      public var searchSearchPlaceholder: RswiftResources.StringResource { .init(key: "search.searchPlaceholder", tableName: "Localizable", source: source, developmentValue: "Search for a movie, TV series...", comment: nil) }

      /// en translation: About Us
      ///
      /// Key: settings.aboutUsTitle
      ///
      /// Locales: en
      public var settingsAboutUsTitle: RswiftResources.StringResource { .init(key: "settings.aboutUsTitle", tableName: "Localizable", source: source, developmentValue: "About Us", comment: nil) }

      /// en translation: Settings
      ///
      /// Key: settings.navigationTitle
      ///
      /// Locales: en
      public var settingsNavigationTitle: RswiftResources.StringResource { .init(key: "settings.navigationTitle", tableName: "Localizable", source: source, developmentValue: "Settings", comment: nil) }

      /// en translation: Privacy Policy
      ///
      /// Key: settings.privacyPolicyTitle
      ///
      /// Locales: en
      public var settingsPrivacyPolicyTitle: RswiftResources.StringResource { .init(key: "settings.privacyPolicyTitle", tableName: "Localizable", source: source, developmentValue: "Privacy Policy", comment: nil) }

      /// en translation: Rate this App
      ///
      /// Key: settings.rateThisAppTitle
      ///
      /// Locales: en
      public var settingsRateThisAppTitle: RswiftResources.StringResource { .init(key: "settings.rateThisAppTitle", tableName: "Localizable", source: source, developmentValue: "Rate this App", comment: nil) }

      /// en translation: TMDB API
      ///
      /// Key: settings.tmdbAPITitle
      ///
      /// Locales: en
      public var settingsTmdbAPITitle: RswiftResources.StringResource { .init(key: "settings.tmdbAPITitle", tableName: "Localizable", source: source, developmentValue: "TMDB API", comment: nil) }

      /// en translation: Buy
      ///
      /// Key: whereToWatch.buyTitle
      ///
      /// Locales: en
      public var whereToWatchBuyTitle: RswiftResources.StringResource { .init(key: "whereToWatch.buyTitle", tableName: "Localizable", source: source, developmentValue: "Buy", comment: nil) }

      /// en translation: Where to Watch
      ///
      /// Key: whereToWatch.navigationTitle
      ///
      /// Locales: en
      public var whereToWatchNavigationTitle: RswiftResources.StringResource { .init(key: "whereToWatch.navigationTitle", tableName: "Localizable", source: source, developmentValue: "Where to Watch", comment: nil) }

      /// en translation: Select country
      ///
      /// Key: whereToWatch.selectCountryTitle
      ///
      /// Locales: en
      public var whereToWatchSelectCountryTitle: RswiftResources.StringResource { .init(key: "whereToWatch.selectCountryTitle", tableName: "Localizable", source: source, developmentValue: "Select country", comment: nil) }

      /// en translation: Stream
      ///
      /// Key: whereToWatch.streamTitle
      ///
      /// Locales: en
      public var whereToWatchStreamTitle: RswiftResources.StringResource { .init(key: "whereToWatch.streamTitle", tableName: "Localizable", source: source, developmentValue: "Stream", comment: nil) }
    }
  }
}